# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "46cefe5529146b71c6b9d64de164911b"
application_url = "http://localhost:3456"
embedded = true
name = "TTP Dashboard"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ ]
